sonar.projectKey=Social-Pro-Back-end

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Social Pro Backend
sonar.projectVersion=1.0

# Thêm thông tin về SonarCloud
sonar.host.url=https://sonarcloud.io
sonar.organization=your-organization

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src/main/java/
sonar.java.binaries=target/classes 
sonar.language=java

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8